frr version 8.5
frr defaults traditional
hostname isp-rtr
!
interface eth1
 ip address 203.0.113.1/30
!
interface lo
 ip address 10.0.255.1/32
!
router bgp 65000
 bgp router-id 10.0.255.1
 neighbor 203.0.113.2 remote-as 65001
 !
 address-family ipv4 unicast
  network 0.0.0.0/0
 exit-address-family
!
ip route 0.0.0.0/0 blackhole
!
line vty
!
