---
- name: Configure branch office lab hosts
  hosts: lab_hosts
  gather_facts: false
  tasks:
    - name: Assign IP address to interface
      ansible.builtin.raw: ip addr add {{ network.ip }} dev {{ network.interface }}
      ignore_errors: true

    - name: Set default gateway
      ansible.builtin.raw: ip route replace default via {{ network.gateway }}
      ignore_errors: true
