frr version 8.4_git
frr defaults traditional
hostname isp-rtr
no ipv6 forwarding
!
ip route 0.0.0.0/0 blackhole
!
interface eth1
 ip address 203.0.113.1/30
exit
!
interface lo
 ip address 10.0.255.1/32
exit
!
router bgp 65000
 bgp router-id 10.0.255.1
 neighbor 203.0.113.2 remote-as 65001
 !
 address-family ipv4 unicast
  network 0.0.0.0/0
  neighbor 203.0.113.2 route-map PERMIT-ALL in
  neighbor 203.0.113.2 route-map PERMIT-ALL out
 exit-address-family
exit
!
route-map PERMIT-ALL permit 10
exit
